/**
 * Build-time emitter. Writes the non-JavaScript artifacts into dist/.
 *
 * Run by `npm run build` after tsup. These outputs are what the PDF, email,
 * canvas and no-build-step consumers read — roughly a third of the fleet's
 * colour surface never touches the React layer at all.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { emitVarsCss, emitGlobalCss } from "./css.js";
import { resolveFlat } from "../theme/buildTheme.js";
import { chartSeries, chartSequential, chartDiverging } from "../tokens/charts.js";
import { elevation, rimFlat, scrim } from "../tokens/elevation.js";
import { statistic, dangerSolid } from "../tokens/status.js";
import { spacing } from "../tokens/text.js";
import { headings, bodyScale } from "../tokens/typography.js";
import type { BrandKey } from "../brands.js";
import type { ColorMode } from "../tokens/surfaces.js";
import type { SurfaceKind } from "../tokens/typography.js";

const OUT = join(process.cwd(), "dist");

const KINDS: SurfaceKind[] = ["staff", "customer"];
const BRANDS: BrandKey[] = ["beastmode", "estore", "gotyaback"];
const MODES: ColorMode[] = ["light", "dark"];

function buildTokensJson() {
  const bySurface: Record<string, unknown> = {};

  for (const kind of KINDS) {
    for (const brand of BRANDS) {
      // A staff surface is always indigo, so emitting it once per brand would
      // be three identical copies.
      if (kind === "staff" && brand !== "beastmode") continue;
      for (const mode of MODES) {
        const key = kind === "staff" ? `staff.${mode}` : `customer.${brand}.${mode}`;
        bySurface[key] = resolveFlat({ kind, brand, mode });
      }
    }
  }

  return {
    $comment:
      "Generated by @beastmode/ui. Flat values for consumers that cannot run React: PDF renderers, email templates, canvas drawing and pre-paint scripts. Do not edit by hand.",
    version: 1,
    surfaces: bySurface,
    shared: {
      elevation,
      rimFlat,
      scrim,
      statistic,
      dangerSolid,
      spacing,
      chart: {
        series: chartSeries,
        sequential: chartSequential,
        diverging: chartDiverging,
      },
      type: { headings, body: bodyScale },
    },
  };
}

mkdirSync(OUT, { recursive: true });
writeFileSync(join(OUT, "tokens.json"), JSON.stringify(buildTokensJson(), null, 2), "utf8");
writeFileSync(join(OUT, "vars.css"), emitVarsCss(), "utf8");
writeFileSync(join(OUT, "global.css"), emitGlobalCss(), "utf8");

console.log("emitted dist/tokens.json, dist/vars.css, dist/global.css");
